(()=>{
 'use strict';
 const library=window.REFERENCE_LIBRARY;if(!library)return;window.REFERENCE_CASES=window.REFERENCE_CASES||[];
 for(const item of window.SWITCH_PROPOSALS||[]){const a=item.annotation;window.REFERENCE_CASES.push({sheet_id:item.sheet_id,annotation_id:a.id,reference_ids:a.reference_ids,candidate_interpretation:a.label,ambiguity:a.note,reviewer_decision:'Check position, qualifiers and approved class. Do not assign pole/gang/way without readable evidence.',review_state:'needs_review'});}
 const el=(tag,text)=>{const e=document.createElement(tag);if(text)e.textContent=text;return e;};
 const panel=el('section');panel.style.cssText='border:2px solid var(--border-focus, #276952);padding:14px;background:var(--surface, #fff);color:var(--text, inherit);border-radius:8px;margin:12px 0';
 panel.append(el('h3','Supporting reference desk'),el('p','The supplied legend for the current drawing comes first, including BDO. PEC is next; other sources are secondary candidates. Conflicts remain unresolved. Reference meanings do not create approved training classes.'),el('p',library.official_completeness));
 const label=el('label','Search reference meanings');const search=el('input');search.placeholder='Try switch, detector, panel, lamp…';label.append(search);panel.append(label);
 const select=el('select');select.style.cssText='width:100%;margin:8px 0';panel.append(select);
 const card=el('div'),cases=el('div');panel.append(card,cases);let currentSheet=null;
 function sourceCard(entry){card.replaceChildren();if(!entry)return;const source=library.sources.find(s=>s.id===entry.source_id);if(!source)return;card.append(el('h3',entry.label),el('p',source.family.toUpperCase()+' · '+entry.locator),el('p',source.edition_status));const img=el('img');img.src=entry.crop;img.alt=entry.label+' source row';img.style.cssText='width:100%;height:auto;max-height:280px;object-fit:contain;background:#fff;border-radius:4px;padding:4px';card.append(img);const a=el('a','Open full source image');a.href=source.image;a.target='_blank';a.rel='noopener';card.append(a,el('p',entry.note||'Compare all defining marks; unresolved when the image does not support a unique meaning.'));
  const button=el('button','Add this reference to my review notes');button.addEventListener('click',()=>{const notes=document.getElementById('notes');notes.value+='\nReference candidate: '+entry.id+' | '+entry.label+' | '+entry.locator+' | source '+source.image+' | SHA256 '+source.sha256+' | meaning/class acceptance pending.';notes.dispatchEvent(new Event('input',{bubbles:true}));});card.append(button);
 }
 function populate(){const term=search.value.toLowerCase(),previous=select.value,legends=new Set(currentSheet?.associated_legend_ids||[]);if(currentSheet?.sheet_type==='legend_reference')legends.add(currentSheet.id);const ranked=e=>legends.has(e.sheet_id)?0:e.group===currentSheet?.group?1:(library.sources.find(s=>s.id===e.source_id)?.family==='drawing'?2:3);const matches=library.entries.filter(e=>(e.label+' '+e.locator+' '+e.id).toLowerCase().includes(term)).sort((a,b)=>ranked(a)-ranked(b));select.replaceChildren();for(const entry of matches){const matchedSource=library.sources.find(s=>s.id===entry.source_id);const family=matchedSource?.family;const prefix=legends.has(entry.sheet_id)?'This drawing · ':family==='pec'?'PEC fallback · ':family==='atp'?'ATP secondary · ':'Drawing-specific · ';const o=el('option',prefix+entry.label);o.value=entry.id;select.append(o);}if(matches.some(e=>e.id===previous))select.value=previous;sourceCard(library.entries.find(e=>e.id===select.value));}
 search.addEventListener('input',populate);select.addEventListener('change',()=>sourceCard(library.entries.find(e=>e.id===select.value)));
 function show(sheet,id){if(!sheet)return;currentSheet=sheet;populate();cases.replaceChildren();const records=window.REFERENCE_CASES.filter(c=>c.sheet_id===sheet.id&&(!id||c.annotation_id===id));cases.append(el('h3','Reference research for '+(id||sheet.filename)));if(!records.length)cases.append(el('p','No new reference-research case for this selection. This does not imply that its annotation is correct.'));for(const r of records){const detail=el('details'),summary=el('summary',r.annotation_id+' · '+r.candidate_interpretation);detail.append(summary,el('p',r.ambiguity),el('p','Decision: '+r.reviewer_decision));for(const ref of r.reference_ids){const b=el('button','Compare '+ref);b.addEventListener('click',()=>{search.value='';populate();select.value=ref;sourceCard(library.entries.find(e=>e.id===ref));});detail.append(b);}if(r.candidate_approved_legend_entry){const b=el('button','Load proposed class into correction controls');b.addEventListener('click',()=>{if(document.getElementById('sheet').value!==r.sheet_id)return;document.getElementById('edit-class').value=(window.LegendRegistry?.resolve(r.candidate_approved_legend_entry))||r.candidate_approved_legend_entry;document.getElementById('edit-class').dispatchEvent(new Event('change'));document.getElementById('edit-layer').value='symbols';document.getElementById('editor-status').textContent='Select '+r.annotation_id+' in the annotation list, then load this class and Apply label / class. This does not approve training.';});detail.append(b);}cases.append(detail);}}
 const all=el('details');all.append(el('summary','All '+library.sources.length+' supplied reference images / rendered pages'));for(const s of library.sources){const p=el('p'),a=el('a',s.id+' · page '+s.page);a.href=s.image;a.target='_blank';a.rel='noopener';p.append(a);all.append(p);}panel.append(all);
 const conflicts=el('details');conflicts.append(el('summary','Conflicts and external research sources'));for(const c of library.conflicts)conflicts.append(el('p',c.symbol+': PEC = '+c.pec+'; ATP = '+c.atp+'. Do not merge meanings.'));for(const source of library.web_sources){const a=el('a',source.title);a.href=source.url;a.target='_blank';a.rel='noopener';conflicts.append(a,el('p',source.finding+' '+source.verification));}panel.append(conflicts);
 const exportButton=el('button','Export reference research report');exportButton.addEventListener('click',()=>{const blob=new Blob([JSON.stringify({schema:'ved-reference-research-v1',library,cases:window.REFERENCE_CASES,training_approved:false},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='ved-drawing-first-reference-research.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});panel.append(exportButton);
 document.getElementById('reference-host')?.append(panel);window.referencePanel={show};populate();const initialSheetId=document.getElementById('sheet')?.value;if(initialSheetId)show((window.ANNOTATION_DATA.sheets||[]).find(s=>s.id===initialSheetId));
})();
