(()=>{
 'use strict';const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';
 function tab(name){for(const id of ['edit','legends','review']){$('panel-'+id).hidden=id!==name;$('tab-'+id).setAttribute('aria-selected',String(id===name));}}
 for(const id of ['edit','legends','review'])$('tab-'+id).addEventListener('click',()=>tab(id));
 function show(s){
    if(!s)return;
    $('annotation-search').value='';window.reviewWorkspace.refreshList();const host=$('own-legend-entries');host.replaceChildren();const associated=$('legends');associated.replaceChildren();const associatedIds=Array.isArray(s?.associated_legend_ids)?s.associated_legend_ids:(Array.isArray(s?.associated_legend_sheets)?s.associated_legend_sheets:[]);for(const id of associatedIds){const source=(window.ANNOTATION_DATA.sheets||[]).find(x=>x.id===id);if(!source||!source.image)continue;const wrap=document.createElement('div');wrap.className='associated-legend';const label=document.createElement('strong');label.textContent=source.filename||source.id;const img=document.createElement('img');img.src=source.image;img.alt=(source.filename||source.id)+' associated legend sheet';wrap.append(label,img);associated.append(wrap);}const associatedDetails=associated.closest('details');if(associatedDetails)associatedDetails.open=associated.children.length>0;
  const targetSheets=[s,...(window.ANNOTATION_DATA.sheets||[]).filter(x=>associatedIds.includes(x.id)&&x.id!==s.id)];
  for(const source of targetSheets){
   for(const a of (source.annotations||[]).filter(a=>a.layer==='legend'&&a.review_state!=='deleted')){
    const card=document.createElement('div');card.className='legend-card';const b=document.createElement('button');b.textContent=a.label;
    b.addEventListener('click',()=>{$('edit-class').value=a.legend_entry;$('edit-label').value=a.label;$('edit-layer').value='symbols';const colorField=$('edit-legend-color');if(colorField)colorField.value=window.reviewWorkspace.getLegendColor(a.legend_entry)||'#1683ff';tab('edit');const selected=window.reviewWorkspace.getSelected?.();if(selected){$('update').click();$('editor-status').textContent='Legend applied to the selected annotation: '+a.label+'.';}else $('editor-status').textContent='Legend loaded. Draw a new box, or select an annotation to apply it.';if(a.geometry?.type==='bbox')window.reviewWorkspace.focusLegendSource?.(source.id,a.geometry.coordinates,a.label);});
    const swatch=document.createElement('input');swatch.type='color';swatch.className='legend-color-swatch';swatch.title='Color used for every annotation of this legend class';swatch.setAttribute('aria-label','Color for '+a.label);swatch.value=window.reviewWorkspace.getLegendColor(a.legend_entry)||'#1683ff';b.style.color=swatch.value;swatch.addEventListener('click',e=>e.stopPropagation());swatch.addEventListener('input',e=>{e.stopPropagation();window.reviewWorkspace.setLegendColor(a.legend_entry,swatch.value);b.style.color=swatch.value;const colorField=$('edit-legend-color');if(colorField&&$('edit-class').value===a.legend_entry)colorField.value=swatch.value;});
    if(a.uploaded_crop){const img=document.createElement('img');img.src=a.uploaded_crop;img.alt=a.label+' (uploaded legend crop)';img.style.cssText='width:100%;height:80px;object-fit:contain;background:#fff';card.append(img);const tag=document.createElement('small');tag.textContent='Uploaded reference — not part of the original drawing legend.';card.append(tag);}
    else if(a.geometry?.type==='bbox'&&source.image){const [x,y,r,bottom]=a.geometry.coordinates;const svg=document.createElementNS(NS,'svg');svg.setAttribute('viewBox',[x,y,r-x,bottom-y].join(' '));svg.setAttribute('role','img');svg.setAttribute('aria-label',a.label+' from this drawing legend');const image=document.createElementNS(NS,'image');image.setAttribute('href',source.image);image.setAttribute('width',source.width);image.setAttribute('height',source.height);svg.append(image);card.append(svg);}const row=document.createElement('div');row.className='legend-row';row.append(swatch,b);card.append(row);if(a.class_state==='user_defined_legend_source'){const remove=document.createElement('button');remove.className='danger small';remove.textContent='Delete uploaded legend';remove.addEventListener('click',()=>{if(window.reviewWorkspace.removeAnnotationById(a.id)){show(window.reviewWorkspace.getCurrent());}});card.append(remove);}host.append(card);
   }
  }
  if(!host.children.length){const p=document.createElement('p');p.textContent='No embedded/associated legend indexed for this drawing. Use references as candidates and leave unclear marks unresolved.';host.append(p);}
 }
 window.workspaceUI={show,selected:()=>tab('edit')};show(window.reviewWorkspace.getCurrent());
})();
